# Production specific properties

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: password
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
