# Production specific properties

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:15432/cisq1-lingo
    username: admin
    password: admin
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
