# General Application Properties

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update

debug: false

# logging.level.org.springframework.web: DEBUG
# logging.level.root: DEBUG

server:
  port: 8080
  servlet:
    context-path: /
