# Production specific properties

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:15432/cisq1-lingo
    username: cisq1-lingo
    password: cisq1-lingo
    initialization-mode: always
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
